import {
  AgentInfo,
  Lead,
  Invoice,
  Employee,
  InventoryItem,
  SupportTicket,
  Workflow,
  ProactiveAlert,
} from '@/types';

export const MOCK_AGENTS: AgentInfo[] = [
  {
    id: 'CEO',
    name: 'CEO Agent',
    roleTitle: 'Strategic Executive Governance',
    domain: 'Executive Strategy',
    status: 'ACTIVE',
    avatarColor: 'bg-blue-600',
    description: 'Executive summaries, cross-agent alignment, strategic decision oversight.',
    tasksCompleted: 142,
  },
  {
    id: 'Sales',
    name: 'Sales Agent',
    roleTitle: 'CRM & Pipeline Lead',
    domain: 'Sales & CRM',
    status: 'PROCESSING',
    avatarColor: 'bg-emerald-600',
    description: 'Lead scoring, stage tracking, proposal drafting, CRM deal updates.',
    tasksCompleted: 489,
  },
  {
    id: 'Marketing',
    name: 'Marketing Agent',
    roleTitle: 'Campaign & Copy Director',
    domain: 'Marketing',
    status: 'IDLE',
    avatarColor: 'bg-purple-600',
    description: 'Ad copy generation, social media post creation, campaign performance.',
    tasksCompleted: 215,
  },
  {
    id: 'Finance',
    name: 'Finance Agent',
    roleTitle: 'Invoicing & Payroll Manager',
    domain: 'Finance & Accounting',
    status: 'ACTIVE',
    avatarColor: 'bg-amber-600',
    description: 'Invoice PDF creation, tax calculation, overdue payment alerts, payroll.',
    tasksCompleted: 612,
  },
  {
    id: 'HR',
    name: 'HR Agent',
    roleTitle: 'People & Culture Partner',
    domain: 'Human Resources',
    status: 'IDLE',
    avatarColor: 'bg-pink-600',
    description: 'Leave approvals, employee onboarding, performance reviews, salary slips.',
    tasksCompleted: 184,
  },
  {
    id: 'Support',
    name: 'Support Agent',
    roleTitle: 'Customer Helpdesk Lead',
    domain: 'Customer Success',
    status: 'PROCESSING',
    avatarColor: 'bg-cyan-600',
    description: 'Ticket routing, SLA breach prevention, automated response resolution.',
    tasksCompleted: 830,
  },
  {
    id: 'Analytics',
    name: 'Analytics Agent',
    roleTitle: 'Business Intelligence Architect',
    domain: 'Data Analytics',
    status: 'ACTIVE',
    avatarColor: 'bg-indigo-600',
    description: 'Real-time KPI calculation, revenue forecasting, chart metrics generator.',
    tasksCompleted: 520,
  },
  {
    id: 'Database',
    name: 'Database Agent',
    roleTitle: 'Schema & Query Validator',
    domain: 'Data Engineering',
    status: 'IDLE',
    avatarColor: 'bg-violet-600',
    description: 'Schema autodiscovery, SQL validation, data integrity checks.',
    tasksCompleted: 340,
  },
  {
    id: 'Workflow',
    name: 'Workflow Planner',
    roleTitle: 'Automation DAG Architect',
    domain: 'Workflow Engine',
    status: 'ACTIVE',
    avatarColor: 'bg-sky-600',
    description: 'Converts natural language into runnable Directed Acyclic Graphs (DAGs).',
    tasksCompleted: 755,
  },
  {
    id: 'Scheduler',
    name: 'Scheduler Agent',
    roleTitle: 'Calendar & Time Coordinator',
    domain: 'Operations',
    status: 'IDLE',
    avatarColor: 'bg-teal-600',
    description: 'Meeting scheduling, calendar conflict resolution, follow-up reminders.',
    tasksCompleted: 390,
  },
  {
    id: 'Document',
    name: 'Document Agent',
    roleTitle: 'Multi-Format File Specialist',
    domain: 'Document AI',
    status: 'IDLE',
    avatarColor: 'bg-orange-600',
    description: 'Parses PDFs, Word docs, invoices, contracts, and extracts key fields.',
    tasksCompleted: 445,
  },
  {
    id: 'Email',
    name: 'Email & Comm Agent',
    roleTitle: 'Omnichannel Communicator',
    domain: 'Communication',
    status: 'PROCESSING',
    avatarColor: 'bg-rose-600',
    description: 'Drafts emails, dispatches Slack alerts, WhatsApp messages, and SMS.',
    tasksCompleted: 910,
  },
  {
    id: 'Knowledge',
    name: 'Knowledge RAG Agent',
    roleTitle: 'Semantic Vector Specialist',
    domain: 'RAG Knowledge',
    status: 'ACTIVE',
    avatarColor: 'bg-lime-600',
    description: 'Document chunking, HNSW vector search, exact line-level source citations.',
    tasksCompleted: 670,
  },
  {
    id: 'Reporting',
    name: 'Reporting Agent',
    roleTitle: 'Executive Report Compiler',
    domain: 'Reporting',
    status: 'IDLE',
    avatarColor: 'bg-fuchsia-600',
    description: 'Generates daily/weekly executive reports exportable as PDF/Excel.',
    tasksCompleted: 295,
  },
  {
    id: 'Security',
    name: 'Security & Audit Agent',
    roleTitle: 'RBAC & Compliance Shield',
    domain: 'Enterprise Security',
    status: 'ACTIVE',
    avatarColor: 'bg-red-600',
    description: '3-tier RBAC enforcement, prompt injection filtering, immutable audit log.',
    tasksCompleted: 1150,
  },
];

export const MOCK_LEADS: Lead[] = [
  { id: 'LD-101', name: 'Vikram Sharma', company: 'Apex Tech Solutions', email: 'vikram@apextech.in', phone: '+91 98765 43210', value: 125000, status: 'PROPOSAL', assignedAgent: 'Sales Agent' },
  { id: 'LD-102', name: 'Ananya Reddy', company: 'Hyderabad Pharma Ltd', email: 'ananya@hydpharma.com', phone: '+91 98123 45678', value: 340000, status: 'WON', assignedAgent: 'Sales Agent' },
  { id: 'LD-103', name: 'Rahul Verma', company: 'Bangalore AI Labs', email: 'rahul@blrai.io', phone: '+91 97654 32109', value: 85000, status: 'QUALIFIED', assignedAgent: 'Sales Agent' },
  { id: 'LD-104', name: 'Priya Sundaram', company: 'Chennai Logistics', email: 'priya@clogistics.in', phone: '+91 99887 76655', value: 210000, status: 'CONTACTED', assignedAgent: 'Sales Agent' },
  { id: 'LD-105', name: 'Karthik Menon', company: 'Kochi Renewable Energy', email: 'karthik@kochienergy.org', phone: '+91 94433 22110', value: 160000, status: 'NEW', assignedAgent: 'Sales Agent' },
];

export const MOCK_INVOICES: Invoice[] = [
  { id: 'INV-2026-001', clientName: 'Hyderabad Pharma Ltd', amount: 340000, dueDate: '2026-09-25', status: 'PAID', itemsCount: 4 },
  { id: 'INV-2026-002', clientName: 'Apex Tech Solutions', amount: 125000, dueDate: '2026-09-10', status: 'OVERDUE', itemsCount: 2 },
  { id: 'INV-2026-003', clientName: 'Chennai Logistics', amount: 95000, dueDate: '2026-09-30', status: 'PENDING', itemsCount: 3 },
  { id: 'INV-2026-004', clientName: 'Bangalore AI Labs', amount: 85000, dueDate: '2026-10-05', status: 'PENDING', itemsCount: 1 },
];

export const MOCK_EMPLOYEES: Employee[] = [
  { id: 'EMP-01', name: 'Rajesh Kumar', role: 'Sales Manager', department: 'Sales', status: 'ACTIVE', salary: 120000 },
  { id: 'EMP-02', name: 'Sravani Rao', role: 'Senior AI Engineer', department: 'Engineering', status: 'ACTIVE', salary: 180000 },
  { id: 'EMP-03', name: 'Amit Patel', role: 'Finance Director', department: 'Finance', status: 'ACTIVE', salary: 195000 },
  { id: 'EMP-04', name: 'Deepa Nair', role: 'Customer Support Lead', department: 'Support', status: 'ON_LEAVE', salary: 95000 },
];

export const MOCK_INVENTORY: InventoryItem[] = [
  { id: 'SKU-8801', productName: 'Enterprise AI Gateway Hub', sku: 'EAG-8801', quantity: 45, minThreshold: 10, unitPrice: 2500, status: 'IN_STOCK' },
  { id: 'SKU-8802', productName: 'Multilingual Voice Micro-Server', sku: 'MVS-8802', quantity: 4, minThreshold: 15, unitPrice: 1800, status: 'LOW_STOCK' },
  { id: 'SKU-8803', productName: 'Vector Edge Neural Processing Unit', sku: 'NPU-8803', quantity: 0, minThreshold: 5, unitPrice: 4200, status: 'OUT_OF_STOCK' },
];

export const MOCK_TICKETS: SupportTicket[] = [
  { id: 'TCK-501', customerName: 'Apex Tech Solutions', subject: 'API Rate limit exceeded on Telugu Voice Synthesizer', priority: 'HIGH', status: 'OPEN', assignedAgent: 'Support' },
  { id: 'TCK-502', customerName: 'Bangalore AI Labs', subject: 'Invoice PDF export missing GST tax break-up', priority: 'MEDIUM', status: 'IN_PROGRESS', assignedAgent: 'Finance' },
  { id: 'TCK-503', customerName: 'Chennai Logistics', subject: 'Requesting custom Slack webhook notification integration', priority: 'LOW', status: 'RESOLVED', assignedAgent: 'Workflow' },
];

export const MOCK_WORKFLOWS: Workflow[] = [
  {
    id: 'WF-1',
    name: 'New Contact Form Lead Onboarding',
    naturalTrigger: 'When a new contact form lead arrives, create CRM lead, assign to Sales Manager, send welcome email & remind in 48h.',
    active: true,
    successRate: 98.4,
    lastRun: '12 mins ago',
    nodes: [
      { id: 'N1', label: 'Trigger: New Contact Form Submission', type: 'TRIGGER', agent: 'Sales', status: 'COMPLETED' },
      { id: 'N2', label: 'Action 1: Create CRM Lead Record', type: 'ACTION', agent: 'Sales', status: 'COMPLETED' },
      { id: 'N3', label: 'Action 2: Send Welcome Email via Communications Agent', type: 'ACTION', agent: 'Email', status: 'COMPLETED' },
      { id: 'N4', label: 'Action 3: Schedule 48h Follow-up Reminder', type: 'ACTION', agent: 'Scheduler', status: 'PENDING' },
    ],
  },
  {
    id: 'WF-2',
    name: 'Overdue Invoice Recovery & Slack Alert',
    naturalTrigger: 'When invoice is overdue by >5 days, generate payment link, post alert to Slack, and log audit entry.',
    active: true,
    successRate: 96.1,
    lastRun: '1 hour ago',
    nodes: [
      { id: 'N1', label: 'Trigger: Invoice Overdue > 5 Days', type: 'TRIGGER', agent: 'Finance', status: 'COMPLETED' },
      { id: 'N2', label: 'Action 1: Generate Payment Recovery Link', type: 'ACTION', agent: 'Finance', status: 'COMPLETED' },
      { id: 'N3', label: 'Action 2: Post Slack Warning to #finance-alerts', type: 'ACTION', agent: 'Email', status: 'COMPLETED' },
      { id: 'N4', label: 'Action 3: Record Audit Entry in Security Log', type: 'ACTION', agent: 'Security', status: 'COMPLETED' },
    ],
  },
];

export const MOCK_ALERTS: ProactiveAlert[] = [
  {
    id: 'ALT-01',
    type: 'OVERDUE_INVOICE',
    title: 'Overdue Invoice Detected (#INV-2026-002)',
    description: 'Apex Tech Solutions invoice ($125,000) is past 8 days due. AI recommends sending polite reminder email.',
    severity: 'WARNING',
    timestamp: '10 mins ago',
    recommendedAction: {
      id: 'ACT-901',
      title: 'Send Payment Reminder Email to Apex Tech Solutions',
      description: 'Email Agent has prepared payment reminder draft with updated UPI / bank details.',
      agent: 'Finance',
      module: 'Finance',
      details: { client: 'Apex Tech Solutions', amount: 125000, invoiceId: 'INV-2026-002' },
      status: 'PENDING',
      confirmLabel: 'Approve & Send Email',
    },
  },
  {
    id: 'ALT-02',
    type: 'LOW_STOCK',
    title: 'Low Inventory Alert (SKU-8802)',
    description: 'Multilingual Voice Micro-Server stock count is 4 (below minimum threshold of 15).',
    severity: 'CRITICAL',
    timestamp: '25 mins ago',
    recommendedAction: {
      id: 'ACT-902',
      title: 'Reorder 20 Units of Multilingual Voice Micro-Server',
      description: 'Document Agent drafted purchase order for supplier review.',
      agent: 'Document',
      module: 'Inventory',
      details: { sku: 'SKU-8802', reorderQty: 20, estimatedCost: 36000 },
      status: 'PENDING',
      confirmLabel: 'Approve Purchase Order',
    },
  },
];
